version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: '08:00'
    timezone: US/Pacific
  open-pull-requests-limit: 10
  target-branch: mpcontribs
