version: "3"

networks:
 kong-net:
  driver: bridge

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:1.5
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:1.5
    restart: always
    networks:
      - kong-net
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - 8001:8001
      - 8000:8000


  #######################################
  # Konga Dashboard
  #######################################
  konga:
      build: .
      environment:
          - KONG_URL=$KONG_URL
          - KONGA_ADMIN_USERNAME=$KONGA_ADMIN_USERNAME
          - KONGA_ADMIN_EMAIL=$KONGA_ADMIN_EMAIL
          - KONGA_ADMIN_FIRSTNAME=$KONGA_ADMIN_FIRSTNAME
          - KONGA_ADMIN_LASTNAME=$KONGA_ADMIN_LASTNAME
          - KONGA_ADMIN_PASSWORD=$KONGA_ADMIN_PASSWORD
          - KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE=/app/kong_node.data
          - KONGA_SEED_USER_DATA_SOURCE_FILE=/app/userdb.data
      ports:
          - "1337:1337"
